ユーザーCRUD実装
Shunsuke-Suzuki/johnson_b pull request #2
Opened 2020-09-21 09:32 UTC by Shunsuke-Suzuki

ユーザーのCRUDとsession_controllerの実装まで行った
ログインの保持とかそこらへんはやってないお

2020-09-22 23:42 UTC, white0221 commented on app/controllers/api/v1/sessions_controller.rb
> +      def new
new アクションいらないと思うー

2020-09-22 23:42 UTC, white0221 commented on config/routes.rb
> +      resources :users
new アクションとか無いので、 only: %i[create index show update destroy] が良いと思うー

2020-09-22 23:45 UTC, white0221 commented
コーディング規約的な部分と、API実装としての約束事を決めてなかった

コーディング規約的な部分
- ファイルの末尾には必ず改行がほしい

API側の約束
- 現状、`{ message: 'ok' }` を返しているけど、文字列よりも数字が嬉しいかなあ
例えば、create, update, destroyの正常成功時は 1000 を返して、異常時は1200 を返すみたいな方がフロント的には嬉しい

2020-09-23 00:34 UTC, Shunsuke-Suzuki commented on app/controllers/api/v1/sessions_controller.rb
> +      def new
消す！

2020-09-23 01:00 UTC, Shunsuke-Suzuki commented on config/routes.rb
> +      resources :users
修正！

2020-09-23 01:04 UTC, Shunsuke-Suzuki commented
> コーディング規約的な部分
ここに関しては別途rubocopとCI導入のPR作る時
に決めるとするか！

> API実装としての約束事
ここは無知すぎるので調べてからツッチーに見せられるような形でレビューを投げさせてもらいたい。
https://qiita.com/takahyon/items/399e3d5781e0f6c73e06
これ使ってみたい

2020-09-26 13:20 UTC, white0221 commented
api blueprint を使わなくても、mdでdocsを書けばそれでよさそう

2020-09-26 13:22 UTC, white0221 requested changes
API仕様書を書いてほしい

2020-10-04 08:27 UTC, Shunsuke-Suzuki commented
@white0221 🙇🏼‍♂️

2020-10-04 09:13 UTC, Shunsuke-Suzuki commented
@white0221 🙇🏼‍♂️🙇🏼‍♂️

2020-10-04 10:45 UTC, Shunsuke-Suzuki commented
@white0221 🙇🏼‍♂️🙇🏼‍♂️🙇🏼‍♂️

2020-10-05 00:49 UTC, Shunsuke-Suzuki commented
かなり強引にworkspace.xmlを削除した。あんまり対応が書かれている記事を見ないのでこの方法が正しいかはよくわかってない。

supplierの.gitignoreには/.ideaのみの記述だったから、そもそもなんでコミット対象になってしまったのかも謎のまま。

一旦はこのまま進めていこうと思う・

2020-10-05 01:11 UTC, white0221 approved these changes

2020-11-08 04:22 UTC, merged